package com.tneciv.poseidon.entity;

import java.util.Date;

public class Journal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journal.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journal.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journal.journal_id
     *
     * @mbg.generated
     */
    private Integer journalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journal.key_words
     *
     * @mbg.generated
     */
    private String keyWords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journal.vol_cover_img
     *
     * @mbg.generated
     */
    private String volCoverImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journal.tracks
     *
     * @mbg.generated
     */
    private String tracks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journal.relative_vols
     *
     * @mbg.generated
     */
    private String relativeVols;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journal.vol_date
     *
     * @mbg.generated
     */
    private String volDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journal.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journal.vol_desc
     *
     * @mbg.generated
     */
    private String volDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    public Journal(Integer id, String title, Integer journalId, String keyWords, String volCoverImg, String tracks, String relativeVols, String volDate, Date createTime, String volDesc) {
        this.id = id;
        this.title = title;
        this.journalId = journalId;
        this.keyWords = keyWords;
        this.volCoverImg = volCoverImg;
        this.tracks = tracks;
        this.relativeVols = relativeVols;
        this.volDate = volDate;
        this.createTime = createTime;
        this.volDesc = volDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    public Journal() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journal.id
     *
     * @return the value of journal.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journal.id
     *
     * @param id the value for journal.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journal.title
     *
     * @return the value of journal.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journal.title
     *
     * @param title the value for journal.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journal.journal_id
     *
     * @return the value of journal.journal_id
     *
     * @mbg.generated
     */
    public Integer getJournalId() {
        return journalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journal.journal_id
     *
     * @param journalId the value for journal.journal_id
     *
     * @mbg.generated
     */
    public void setJournalId(Integer journalId) {
        this.journalId = journalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journal.key_words
     *
     * @return the value of journal.key_words
     *
     * @mbg.generated
     */
    public String getKeyWords() {
        return keyWords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journal.key_words
     *
     * @param keyWords the value for journal.key_words
     *
     * @mbg.generated
     */
    public void setKeyWords(String keyWords) {
        this.keyWords = keyWords == null ? null : keyWords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journal.vol_cover_img
     *
     * @return the value of journal.vol_cover_img
     *
     * @mbg.generated
     */
    public String getVolCoverImg() {
        return volCoverImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journal.vol_cover_img
     *
     * @param volCoverImg the value for journal.vol_cover_img
     *
     * @mbg.generated
     */
    public void setVolCoverImg(String volCoverImg) {
        this.volCoverImg = volCoverImg == null ? null : volCoverImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journal.tracks
     *
     * @return the value of journal.tracks
     *
     * @mbg.generated
     */
    public String getTracks() {
        return tracks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journal.tracks
     *
     * @param tracks the value for journal.tracks
     *
     * @mbg.generated
     */
    public void setTracks(String tracks) {
        this.tracks = tracks == null ? null : tracks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journal.relative_vols
     *
     * @return the value of journal.relative_vols
     *
     * @mbg.generated
     */
    public String getRelativeVols() {
        return relativeVols;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journal.relative_vols
     *
     * @param relativeVols the value for journal.relative_vols
     *
     * @mbg.generated
     */
    public void setRelativeVols(String relativeVols) {
        this.relativeVols = relativeVols == null ? null : relativeVols.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journal.vol_date
     *
     * @return the value of journal.vol_date
     *
     * @mbg.generated
     */
    public String getVolDate() {
        return volDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journal.vol_date
     *
     * @param volDate the value for journal.vol_date
     *
     * @mbg.generated
     */
    public void setVolDate(String volDate) {
        this.volDate = volDate == null ? null : volDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journal.create_time
     *
     * @return the value of journal.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journal.create_time
     *
     * @param createTime the value for journal.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journal.vol_desc
     *
     * @return the value of journal.vol_desc
     *
     * @mbg.generated
     */
    public String getVolDesc() {
        return volDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journal.vol_desc
     *
     * @param volDesc the value for journal.vol_desc
     *
     * @mbg.generated
     */
    public void setVolDesc(String volDesc) {
        this.volDesc = volDesc == null ? null : volDesc.trim();
    }
}