package com.tneciv.poseidon.dao;

import com.tneciv.poseidon.entity.Journal;
import com.tneciv.poseidon.entity.JournalExample.Criteria;
import com.tneciv.poseidon.entity.JournalExample.Criterion;
import com.tneciv.poseidon.entity.JournalExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class JournalSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    public String countByExample(JournalExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("journal");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    public String deleteByExample(JournalExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("journal");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    public String insertSelective(Journal record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("journal");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getTitle() != null) {
            sql.VALUES("title", "#{title,jdbcType=VARCHAR}");
        }
        
        if (record.getJournalId() != null) {
            sql.VALUES("journal_id", "#{journalId,jdbcType=INTEGER}");
        }
        
        if (record.getKeyWords() != null) {
            sql.VALUES("key_words", "#{keyWords,jdbcType=VARCHAR}");
        }
        
        if (record.getVolCoverImg() != null) {
            sql.VALUES("vol_cover_img", "#{volCoverImg,jdbcType=VARCHAR}");
        }
        
        if (record.getTracks() != null) {
            sql.VALUES("tracks", "#{tracks,jdbcType=VARCHAR}");
        }
        
        if (record.getRelativeVols() != null) {
            sql.VALUES("relative_vols", "#{relativeVols,jdbcType=VARCHAR}");
        }
        
        if (record.getVolDate() != null) {
            sql.VALUES("vol_date", "#{volDate,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getVolDesc() != null) {
            sql.VALUES("vol_desc", "#{volDesc,jdbcType=LONGVARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    public String selectByExampleWithBLOBs(JournalExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("title");
        sql.SELECT("journal_id");
        sql.SELECT("key_words");
        sql.SELECT("vol_cover_img");
        sql.SELECT("tracks");
        sql.SELECT("relative_vols");
        sql.SELECT("vol_date");
        sql.SELECT("create_time");
        sql.SELECT("vol_desc");
        sql.FROM("journal");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    public String selectByExample(JournalExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("title");
        sql.SELECT("journal_id");
        sql.SELECT("key_words");
        sql.SELECT("vol_cover_img");
        sql.SELECT("tracks");
        sql.SELECT("relative_vols");
        sql.SELECT("vol_date");
        sql.SELECT("create_time");
        sql.FROM("journal");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Journal record = (Journal) parameter.get("record");
        JournalExample example = (JournalExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("journal");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getTitle() != null) {
            sql.SET("title = #{record.title,jdbcType=VARCHAR}");
        }
        
        if (record.getJournalId() != null) {
            sql.SET("journal_id = #{record.journalId,jdbcType=INTEGER}");
        }
        
        if (record.getKeyWords() != null) {
            sql.SET("key_words = #{record.keyWords,jdbcType=VARCHAR}");
        }
        
        if (record.getVolCoverImg() != null) {
            sql.SET("vol_cover_img = #{record.volCoverImg,jdbcType=VARCHAR}");
        }
        
        if (record.getTracks() != null) {
            sql.SET("tracks = #{record.tracks,jdbcType=VARCHAR}");
        }
        
        if (record.getRelativeVols() != null) {
            sql.SET("relative_vols = #{record.relativeVols,jdbcType=VARCHAR}");
        }
        
        if (record.getVolDate() != null) {
            sql.SET("vol_date = #{record.volDate,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getVolDesc() != null) {
            sql.SET("vol_desc = #{record.volDesc,jdbcType=LONGVARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("journal");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("title = #{record.title,jdbcType=VARCHAR}");
        sql.SET("journal_id = #{record.journalId,jdbcType=INTEGER}");
        sql.SET("key_words = #{record.keyWords,jdbcType=VARCHAR}");
        sql.SET("vol_cover_img = #{record.volCoverImg,jdbcType=VARCHAR}");
        sql.SET("tracks = #{record.tracks,jdbcType=VARCHAR}");
        sql.SET("relative_vols = #{record.relativeVols,jdbcType=VARCHAR}");
        sql.SET("vol_date = #{record.volDate,jdbcType=VARCHAR}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("vol_desc = #{record.volDesc,jdbcType=LONGVARCHAR}");
        
        JournalExample example = (JournalExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("journal");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("title = #{record.title,jdbcType=VARCHAR}");
        sql.SET("journal_id = #{record.journalId,jdbcType=INTEGER}");
        sql.SET("key_words = #{record.keyWords,jdbcType=VARCHAR}");
        sql.SET("vol_cover_img = #{record.volCoverImg,jdbcType=VARCHAR}");
        sql.SET("tracks = #{record.tracks,jdbcType=VARCHAR}");
        sql.SET("relative_vols = #{record.relativeVols,jdbcType=VARCHAR}");
        sql.SET("vol_date = #{record.volDate,jdbcType=VARCHAR}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        
        JournalExample example = (JournalExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Journal record) {
        SQL sql = new SQL();
        sql.UPDATE("journal");
        
        if (record.getTitle() != null) {
            sql.SET("title = #{title,jdbcType=VARCHAR}");
        }
        
        if (record.getJournalId() != null) {
            sql.SET("journal_id = #{journalId,jdbcType=INTEGER}");
        }
        
        if (record.getKeyWords() != null) {
            sql.SET("key_words = #{keyWords,jdbcType=VARCHAR}");
        }
        
        if (record.getVolCoverImg() != null) {
            sql.SET("vol_cover_img = #{volCoverImg,jdbcType=VARCHAR}");
        }
        
        if (record.getTracks() != null) {
            sql.SET("tracks = #{tracks,jdbcType=VARCHAR}");
        }
        
        if (record.getRelativeVols() != null) {
            sql.SET("relative_vols = #{relativeVols,jdbcType=VARCHAR}");
        }
        
        if (record.getVolDate() != null) {
            sql.SET("vol_date = #{volDate,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getVolDesc() != null) {
            sql.SET("vol_desc = #{volDesc,jdbcType=LONGVARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, JournalExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}