package com.tneciv.poseidon.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JournalExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table journal
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table journal
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table journal
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    public JournalExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journal
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table journal
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andJournalIdIsNull() {
            addCriterion("journal_id is null");
            return (Criteria) this;
        }

        public Criteria andJournalIdIsNotNull() {
            addCriterion("journal_id is not null");
            return (Criteria) this;
        }

        public Criteria andJournalIdEqualTo(Integer value) {
            addCriterion("journal_id =", value, "journalId");
            return (Criteria) this;
        }

        public Criteria andJournalIdNotEqualTo(Integer value) {
            addCriterion("journal_id <>", value, "journalId");
            return (Criteria) this;
        }

        public Criteria andJournalIdGreaterThan(Integer value) {
            addCriterion("journal_id >", value, "journalId");
            return (Criteria) this;
        }

        public Criteria andJournalIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("journal_id >=", value, "journalId");
            return (Criteria) this;
        }

        public Criteria andJournalIdLessThan(Integer value) {
            addCriterion("journal_id <", value, "journalId");
            return (Criteria) this;
        }

        public Criteria andJournalIdLessThanOrEqualTo(Integer value) {
            addCriterion("journal_id <=", value, "journalId");
            return (Criteria) this;
        }

        public Criteria andJournalIdIn(List<Integer> values) {
            addCriterion("journal_id in", values, "journalId");
            return (Criteria) this;
        }

        public Criteria andJournalIdNotIn(List<Integer> values) {
            addCriterion("journal_id not in", values, "journalId");
            return (Criteria) this;
        }

        public Criteria andJournalIdBetween(Integer value1, Integer value2) {
            addCriterion("journal_id between", value1, value2, "journalId");
            return (Criteria) this;
        }

        public Criteria andJournalIdNotBetween(Integer value1, Integer value2) {
            addCriterion("journal_id not between", value1, value2, "journalId");
            return (Criteria) this;
        }

        public Criteria andKeyWordsIsNull() {
            addCriterion("key_words is null");
            return (Criteria) this;
        }

        public Criteria andKeyWordsIsNotNull() {
            addCriterion("key_words is not null");
            return (Criteria) this;
        }

        public Criteria andKeyWordsEqualTo(String value) {
            addCriterion("key_words =", value, "keyWords");
            return (Criteria) this;
        }

        public Criteria andKeyWordsNotEqualTo(String value) {
            addCriterion("key_words <>", value, "keyWords");
            return (Criteria) this;
        }

        public Criteria andKeyWordsGreaterThan(String value) {
            addCriterion("key_words >", value, "keyWords");
            return (Criteria) this;
        }

        public Criteria andKeyWordsGreaterThanOrEqualTo(String value) {
            addCriterion("key_words >=", value, "keyWords");
            return (Criteria) this;
        }

        public Criteria andKeyWordsLessThan(String value) {
            addCriterion("key_words <", value, "keyWords");
            return (Criteria) this;
        }

        public Criteria andKeyWordsLessThanOrEqualTo(String value) {
            addCriterion("key_words <=", value, "keyWords");
            return (Criteria) this;
        }

        public Criteria andKeyWordsLike(String value) {
            addCriterion("key_words like", value, "keyWords");
            return (Criteria) this;
        }

        public Criteria andKeyWordsNotLike(String value) {
            addCriterion("key_words not like", value, "keyWords");
            return (Criteria) this;
        }

        public Criteria andKeyWordsIn(List<String> values) {
            addCriterion("key_words in", values, "keyWords");
            return (Criteria) this;
        }

        public Criteria andKeyWordsNotIn(List<String> values) {
            addCriterion("key_words not in", values, "keyWords");
            return (Criteria) this;
        }

        public Criteria andKeyWordsBetween(String value1, String value2) {
            addCriterion("key_words between", value1, value2, "keyWords");
            return (Criteria) this;
        }

        public Criteria andKeyWordsNotBetween(String value1, String value2) {
            addCriterion("key_words not between", value1, value2, "keyWords");
            return (Criteria) this;
        }

        public Criteria andVolCoverImgIsNull() {
            addCriterion("vol_cover_img is null");
            return (Criteria) this;
        }

        public Criteria andVolCoverImgIsNotNull() {
            addCriterion("vol_cover_img is not null");
            return (Criteria) this;
        }

        public Criteria andVolCoverImgEqualTo(String value) {
            addCriterion("vol_cover_img =", value, "volCoverImg");
            return (Criteria) this;
        }

        public Criteria andVolCoverImgNotEqualTo(String value) {
            addCriterion("vol_cover_img <>", value, "volCoverImg");
            return (Criteria) this;
        }

        public Criteria andVolCoverImgGreaterThan(String value) {
            addCriterion("vol_cover_img >", value, "volCoverImg");
            return (Criteria) this;
        }

        public Criteria andVolCoverImgGreaterThanOrEqualTo(String value) {
            addCriterion("vol_cover_img >=", value, "volCoverImg");
            return (Criteria) this;
        }

        public Criteria andVolCoverImgLessThan(String value) {
            addCriterion("vol_cover_img <", value, "volCoverImg");
            return (Criteria) this;
        }

        public Criteria andVolCoverImgLessThanOrEqualTo(String value) {
            addCriterion("vol_cover_img <=", value, "volCoverImg");
            return (Criteria) this;
        }

        public Criteria andVolCoverImgLike(String value) {
            addCriterion("vol_cover_img like", value, "volCoverImg");
            return (Criteria) this;
        }

        public Criteria andVolCoverImgNotLike(String value) {
            addCriterion("vol_cover_img not like", value, "volCoverImg");
            return (Criteria) this;
        }

        public Criteria andVolCoverImgIn(List<String> values) {
            addCriterion("vol_cover_img in", values, "volCoverImg");
            return (Criteria) this;
        }

        public Criteria andVolCoverImgNotIn(List<String> values) {
            addCriterion("vol_cover_img not in", values, "volCoverImg");
            return (Criteria) this;
        }

        public Criteria andVolCoverImgBetween(String value1, String value2) {
            addCriterion("vol_cover_img between", value1, value2, "volCoverImg");
            return (Criteria) this;
        }

        public Criteria andVolCoverImgNotBetween(String value1, String value2) {
            addCriterion("vol_cover_img not between", value1, value2, "volCoverImg");
            return (Criteria) this;
        }

        public Criteria andTracksIsNull() {
            addCriterion("tracks is null");
            return (Criteria) this;
        }

        public Criteria andTracksIsNotNull() {
            addCriterion("tracks is not null");
            return (Criteria) this;
        }

        public Criteria andTracksEqualTo(String value) {
            addCriterion("tracks =", value, "tracks");
            return (Criteria) this;
        }

        public Criteria andTracksNotEqualTo(String value) {
            addCriterion("tracks <>", value, "tracks");
            return (Criteria) this;
        }

        public Criteria andTracksGreaterThan(String value) {
            addCriterion("tracks >", value, "tracks");
            return (Criteria) this;
        }

        public Criteria andTracksGreaterThanOrEqualTo(String value) {
            addCriterion("tracks >=", value, "tracks");
            return (Criteria) this;
        }

        public Criteria andTracksLessThan(String value) {
            addCriterion("tracks <", value, "tracks");
            return (Criteria) this;
        }

        public Criteria andTracksLessThanOrEqualTo(String value) {
            addCriterion("tracks <=", value, "tracks");
            return (Criteria) this;
        }

        public Criteria andTracksLike(String value) {
            addCriterion("tracks like", value, "tracks");
            return (Criteria) this;
        }

        public Criteria andTracksNotLike(String value) {
            addCriterion("tracks not like", value, "tracks");
            return (Criteria) this;
        }

        public Criteria andTracksIn(List<String> values) {
            addCriterion("tracks in", values, "tracks");
            return (Criteria) this;
        }

        public Criteria andTracksNotIn(List<String> values) {
            addCriterion("tracks not in", values, "tracks");
            return (Criteria) this;
        }

        public Criteria andTracksBetween(String value1, String value2) {
            addCriterion("tracks between", value1, value2, "tracks");
            return (Criteria) this;
        }

        public Criteria andTracksNotBetween(String value1, String value2) {
            addCriterion("tracks not between", value1, value2, "tracks");
            return (Criteria) this;
        }

        public Criteria andRelativeVolsIsNull() {
            addCriterion("relative_vols is null");
            return (Criteria) this;
        }

        public Criteria andRelativeVolsIsNotNull() {
            addCriterion("relative_vols is not null");
            return (Criteria) this;
        }

        public Criteria andRelativeVolsEqualTo(String value) {
            addCriterion("relative_vols =", value, "relativeVols");
            return (Criteria) this;
        }

        public Criteria andRelativeVolsNotEqualTo(String value) {
            addCriterion("relative_vols <>", value, "relativeVols");
            return (Criteria) this;
        }

        public Criteria andRelativeVolsGreaterThan(String value) {
            addCriterion("relative_vols >", value, "relativeVols");
            return (Criteria) this;
        }

        public Criteria andRelativeVolsGreaterThanOrEqualTo(String value) {
            addCriterion("relative_vols >=", value, "relativeVols");
            return (Criteria) this;
        }

        public Criteria andRelativeVolsLessThan(String value) {
            addCriterion("relative_vols <", value, "relativeVols");
            return (Criteria) this;
        }

        public Criteria andRelativeVolsLessThanOrEqualTo(String value) {
            addCriterion("relative_vols <=", value, "relativeVols");
            return (Criteria) this;
        }

        public Criteria andRelativeVolsLike(String value) {
            addCriterion("relative_vols like", value, "relativeVols");
            return (Criteria) this;
        }

        public Criteria andRelativeVolsNotLike(String value) {
            addCriterion("relative_vols not like", value, "relativeVols");
            return (Criteria) this;
        }

        public Criteria andRelativeVolsIn(List<String> values) {
            addCriterion("relative_vols in", values, "relativeVols");
            return (Criteria) this;
        }

        public Criteria andRelativeVolsNotIn(List<String> values) {
            addCriterion("relative_vols not in", values, "relativeVols");
            return (Criteria) this;
        }

        public Criteria andRelativeVolsBetween(String value1, String value2) {
            addCriterion("relative_vols between", value1, value2, "relativeVols");
            return (Criteria) this;
        }

        public Criteria andRelativeVolsNotBetween(String value1, String value2) {
            addCriterion("relative_vols not between", value1, value2, "relativeVols");
            return (Criteria) this;
        }

        public Criteria andVolDateIsNull() {
            addCriterion("vol_date is null");
            return (Criteria) this;
        }

        public Criteria andVolDateIsNotNull() {
            addCriterion("vol_date is not null");
            return (Criteria) this;
        }

        public Criteria andVolDateEqualTo(String value) {
            addCriterion("vol_date =", value, "volDate");
            return (Criteria) this;
        }

        public Criteria andVolDateNotEqualTo(String value) {
            addCriterion("vol_date <>", value, "volDate");
            return (Criteria) this;
        }

        public Criteria andVolDateGreaterThan(String value) {
            addCriterion("vol_date >", value, "volDate");
            return (Criteria) this;
        }

        public Criteria andVolDateGreaterThanOrEqualTo(String value) {
            addCriterion("vol_date >=", value, "volDate");
            return (Criteria) this;
        }

        public Criteria andVolDateLessThan(String value) {
            addCriterion("vol_date <", value, "volDate");
            return (Criteria) this;
        }

        public Criteria andVolDateLessThanOrEqualTo(String value) {
            addCriterion("vol_date <=", value, "volDate");
            return (Criteria) this;
        }

        public Criteria andVolDateLike(String value) {
            addCriterion("vol_date like", value, "volDate");
            return (Criteria) this;
        }

        public Criteria andVolDateNotLike(String value) {
            addCriterion("vol_date not like", value, "volDate");
            return (Criteria) this;
        }

        public Criteria andVolDateIn(List<String> values) {
            addCriterion("vol_date in", values, "volDate");
            return (Criteria) this;
        }

        public Criteria andVolDateNotIn(List<String> values) {
            addCriterion("vol_date not in", values, "volDate");
            return (Criteria) this;
        }

        public Criteria andVolDateBetween(String value1, String value2) {
            addCriterion("vol_date between", value1, value2, "volDate");
            return (Criteria) this;
        }

        public Criteria andVolDateNotBetween(String value1, String value2) {
            addCriterion("vol_date not between", value1, value2, "volDate");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table journal
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table journal
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}